### ISSUE TITLE
[需求] 硬链接目标名能设定成英文吗？

### ISSUE THREAD

**Issue by gogoout** [pofey/movie_robot#204]
```
movie_metadata:
  tmdb:
    api_key: ''
  fanart:
    api_key: ''
  link_template:
    movie:
      filename: '{{name}} ({{year}}) [tmdbid={{tmdbid}}]{%if version %} - {{version}}{% endif %}'
      folder: '{{name}} ({{year}}) [tmdbid={{tmdbid}}]'
    tv:
      filename: '{{name}} S{{season}}E{{ep_start}}{%if ep_end %}-E{{ep_end}}{% endif %}{%if version %} - {{version}}{% endif %}'
      folder: '{{name}} ({{year}}) [tmdbid={{tmdbid}}]'
```

这里的变量`name` 支持使用英文名称吗？
