### ISSUE TITLE
[缺陷]: 馒头港剧能搜索到，但订阅不自动下载

### ISSUE THREAD

**Issue by neroxps** [pofey/movie_robot#495]
### 当前程序版本

0.9.99.0719

### 问题描述

影片名称：童时爱上你
影片馒头内英文名为：Jade Childhood In A Capsule Ep17 HDTV 1080p H264-CNHK
TMDBLink： [https://www.themoviedb.org/tv/204865](https://www.themoviedb.org/tv/204865)
![image](https://user-images.githubusercontent.com/8503224/179883315-f3a2374d-0cdf-4f94-aaaa-92d8862863db.png)
![image](https://user-images.githubusercontent.com/8503224/179883333-d9f97aaa-df44-414f-83c0-a2a92afd9d9d.png)
![image](https://user-images.githubusercontent.com/8503224/179883505-5dbedbf7-5c06-4d11-8d42-a78e17c9dccc.png)
![image](https://user-images.githubusercontent.com/8503224/179884146-eba6b62c-122e-4f22-a918-0902e955810b.png)

### 另外识别不了他依然会链接到目的目录，导致emby 一大堆无法搜刮文件夹
![image](https://user-images.githubusercontent.com/8503224/179888541-1778e793-665e-4aa0-8b3c-737974fe4a4a.png)
![image](https://user-images.githubusercontent.com/8503224/179888680-f2c21e5c-9e03-4cce-bd91-83d4cf2b9643.png)

### 重现步骤

1. 再 Movie_robot 搜索输入：童时爱上你
2. 出现剧集订阅，点击订阅
3. 观察日志如下：
4. 使用手动资源整理的时候，也无法识别出剧集。日志如下：

```bash
movie-robot    | 2022/07/20 10:20:50 - Thread-442 - ERROR: 未能识别影片 内容：/4T/tmpTV/Jade.Childhood In A Capsule.Ep12.HDTV.1080p.H264-CNHK/Jade.Childhood In A Capsule.Ep12.HDTV.1080p.H264-CNHK.ts 文件名: Jade.Childhood In A Capsule.Ep12.HDTV.1080p.H264-CNHK.ts 查询信息: [{'type': 'keyword', 'value': 'Jade Childhood In A Capsule', 'release_year': None}]
movie-robot    | 2022/07/20 10:20:50 - Thread-442 - ERROR: 未能识别影片 内容：/4T/tmpTV/Jade.Childhood In A Capsule.Ep13.HDTV.1080p.H264-CNHK/Jade.Childhood In A Capsule.Ep13.HDTV.1080p.H264-CNHK.ts 文件名: Jade.Childhood In A Capsule.Ep13.HDTV.1080p.H264-CNHK.ts 查询信息: [{'type': 'keyword', 'value': 'Jade Childhood In A Capsule', 'release_year': None}]
movie-robot    | 2022/07/20 10:20:51 - Thread-442 - ERROR: 未能识别影片 内容：/4T/tmpTV/Jade.Childhood In A Capsule.Ep15.HDTV.1080p.H264-CNHK/Jade.Childhood In A Capsule.Ep15.HDTV.1080p.H264-CNHK.ts 文件名: Jade.Childhood In A Capsule.Ep15.HDTV.1080p.H264-CNHK.ts 查询信息: [{'type': 'keyword', 'value': 'Jade Childhood In A Capsule', 'release_year': None}]
movie-robot    | 2022/07/20 10:20:51 - Thread-442 - ERROR: 未能识别影片 内容：/4T/tmpTV/Jade.Childhood In A Capsule.Ep16.HDTV.1080p.H264-CNHK/Jade.Childhood In A Capsule.Ep16.HDTV.1080p.H264-CNHK.ts 文件名: Jade.Childhood In A Capsule.Ep16.HDTV.1080p.H264-CNHK.ts 查询信息: [{'type': 'keyword', 'value': 'Jade Childhood In A Capsule', 'release_year': None}]
```

### 发生问题时系统日志

```shell
movie-robot    | 2022/07/20 10:27:20 - SubConsumer - INFO: 已经开始在站点: 听听歌,馒头 搜索: 童时爱上你,Childhood In A Capsule
movie-robot    | 2022/07/20 10:27:41 - SubConsumer - INFO: 共在2个站点搜索到17条结果，其中馒头最慢，耗费20.34秒
movie-robot    | 2022/07/20 10:27:41 - SubConsumer - INFO: 童时爱上你(2022) 经过系统分析后，没有搜到有效结果。
movie-robot    | 2022/07/20 10:28:07 - SubConsumer - INFO: 已经开始在站点: 听听歌,馒头 搜索: 童时爱上你,Childhood In A Capsule
movie-robot    | 2022/07/20 10:28:21 - SubConsumer - INFO: 共在2个站点搜索到17条结果，其中馒头最慢，耗费13.27秒
movie-robot    | 2022/07/20 10:28:21 - SubConsumer - INFO: 童时爱上你(2022) 经过系统分析后，没有搜到有效结果。
```

### 健康检查

![image](https://user-images.githubusercontent.com/8503224/179883739-05463092-50fd-4c8f-aeb8-afc69181844e.png)

**Comment by pofey** [comment]
种子名的英文名和实际tmdb英文名不符，中文名加前缀也是和实际中文名不符，被过滤符合预期
你设置中开启unknown，就会进unknown了

**Comment by neroxps** [comment]
> 

所以？我要怎么解决？？Jade  很多字幕组翡翠台的电视剧都会加的，意思是现在 movie robot 这种问题不能解决了？

**Comment by neroxps** [comment]
以前的版本是可以的啊，这个剧播出都一直能订阅的。现在更新最近几个版本（具体哪个版本不太清楚了）才不能订阅了，这个问题是不能解决了？

**Comment by neroxps** [comment]
```yaml
### 中文港剧无效关键字
- link: "https://kp.m-team.cc/details.php?id=594357&hit=1"
  titelZhName: "港剧: 智能爱人 全30集 主演：李佳芯 冯盈盈 关楚耀 中粤语双语/简繁字幕"
  titelEnName: "Jade AI Romantic Complete S01 2021 1080p MyVideo WEB-DL AAC2.0 H.264-HDSWEB"
  tmdbCNName: "智能爱人 (2021)"
  tmdbENName: "AI Romantic"
  tmdbLink: "https://www.themoviedb.org/tv/125380-ai-romantic"
  ignoreKey:
    - "Jade"
    - "港剧:"
- link: "https://kp.m-team.cc/details.php?id=593585&hit=1"
  titelZhName: "[港剧] 白色强人2/Big White Duel II 第27-28集"
  titelEnName: "Big White Duel 2022 S02E27-E28 2160p WEB-DL 60fps H265 10bit AAC 2Audio-LeagueWEB"
  tmdbCNName: "白色強人2"
  tmdbENname: "Big White Duel II"
  tmdbLink: "https://www.themoviedb.org/tv/206041-2"
  ignoreKey:
    - "[港剧]"
- link: "https://kp.m-team.cc/details.php?id=588739&hit=1"
  titelZhName: "港剧: 十八年后的终极告白2.0 全20集 主演：谭俊彦 陈山聪 曹永廉 粤语/DVB中英字幕"
  titelEnName: "Jade Brutally Young 2.0 Complete HDTV 720p x264-HDSTV"
  tmdbCNName: "十八年后的终极告白2.0 (2022)"
  tmdbENname: "Brutally Young 2.0"
  tmdbLink: "https://www.themoviedb.org/tv/202803-2-0"
  ignoreKey:
    - "港剧:"
    - "Jade"
- link: "https://kp.m-team.cc/details.php?id=563469&hit=1"
  titelZhName: "港剧 黑金风暴 第17-30集 | 主演：林峯 / 周秀娜 / 黄浩然 国粤双语 60帧"
  titelEnName: "In The Storm S01 2022 2160p WEB-DL AAC H265-HDSWEB"
  tmdbCNName: "黑金风暴 (2022)"
  tmdbENname: null
  tmdbLink: "https://www.themoviedb.org/tv/194828"
  ignoreKey:
    - "港剧"
- link: "https://kp.m-team.cc/details.php?id=563469&hit=1"
  titelZhName: "港剧: 飞虎之壮志英雄 全30集 主演：苗侨伟 黄宗泽 吴卓羲 粤语/DVB简繁中字"
  titelEnName: "Jade Flying Tiger 3 Complete HDTV 1080i H.264-HDSTV"
  tmdbCNName: "飞虎之壮志英雄 (2021)"
  tmdbENname: "Flying Tiger"
  tmdbLink: "https://www.themoviedb.org/tv/153613-3"
  ignoreKey:
    - "港剧:"
    - "Jade"
- link: "https://kp.m-team.cc/details.php?id=592955&hit=1"
  titelZhName: "港劇: 回归 (第3集)[粤语][簡体字幕][郭晉安/陳煒/吳偉豪/周嘉洛 主演][CNHK製作組榮譽出品]"
  titelEnName: "Jade Communion Ep03 HDTV 1080p H264-CNHK"
  tmdbCNName: "回归 (2022)"
  tmdbENname: "Communion"
  tmdbLink: "https://www.themoviedb.org/tv/205768"
  ignoreKey:
    - "港劇:"
    - "Jade"
```
