### ISSUE TITLE
[缺陷]: m-team 剧集 回归（Communion）没有搜索到有效结果

### ISSUE THREAD

**Issue by neroxps** [pofey/movie_robot#532]
### 当前程序版本

0.9.99.0725

### 问题描述

m-team 剧集 回归（Communion）没有搜索到有效结果
剧集链接： [https://kp.m-team.cc/details.php?id=596497&hit=1](https://kp.m-team.cc/details.php?id=596497&hit=1)
经过 #495 关键字忽略依然无法获得正确结果。
请问如何排查？我只有馒头才有这个剧集
我很需要订阅它。

# ！！！！能否做一个完全自定义过滤？？？！！！！！！！！

# ！！！！ 我怀疑是我配置问题，我又全新部署，结果一模一样~！！！！！请问用户如何修复这个问题？？！！！！！！！！！

### 重现步骤

1. 搜索关键词 Communion
2. 点击订阅按钮
3. 观察日志

### 发生问题时系统日志

```shell
movie-robot    | 2022/07/27 10:41:38 - Thread-468 - INFO: 已经开始在站点: 馒头,听听歌 搜索: Communion
movie-robot    | 2022/07/27 10:41:42 - Thread-468 - INFO: 共在2个站点搜索到11条结果，其中馒头最慢，耗费3.97秒
movie-robot    | 2022/07/27 10:41:57 - SubRequestConsumer - INFO: 新增来自admin的订阅: 回归(2022)
movie-robot    | 2022/07/27 10:41:58 - SubConsumer - INFO: 已经开始在站点: 馒头,听听歌 搜索: 回归,Communion
movie-robot    | 2022/07/27 10:42:21 - SubConsumer - INFO: 共在2个站点搜索到165条结果，其中馒头最慢，耗费22.85秒
movie-robot    | 2022/07/27 10:42:22 - SubConsumer - INFO: 回归(2022) 经过系统分析后，没有搜到有效结果。
```

### 健康检查

![image](https://user-images.githubusercontent.com/8503224/181150145-2014b1e2-d51b-4f0b-90e7-0713cd1e0274.png)

**Comment by neroxps** [comment]
# 补充目前所有配置

```
download_client:
- is_default: true
  monitor_all_torrents: false
  name: qb
  need_login: true
  password: password
  site_id: []
  status: 1
  type: qbittorrent
  url: url
  username: username
free_download:
  avg_statistics_period: 5
  enable: false
media_path:
- download_path: /4T/tmpTV
  file_process_mode: link
  qbit_cate: ''
  source_dir: /4T/tmpTV
  target_dir: /4T/TV
  type: tv
- download_path: /4T/movie/tmp-cn
  file_process_mode: link
  qbit_cate: ''
  source_dir: /4T/movie/tmp-cn
  target_dir: /4T/movie/cn
  type: movie
- download_path: /4T/movie/tmp-en
  file_process_mode: link
  qbit_cate: ''
  source_dir: /4T/movie/tmp-en
  target_dir: /4T/movie/en
  type: movie
- download_path: /4T/movie/tmp-hk
  file_process_mode: link
  qbit_cate: ''
  source_dir: /4T/movie/tmp-hk
  target_dir: /4T/movie/hk
  type: movie
media_server:
  default: emby
  emby:
    api_key: api_key
    host: host
    https: false
    port: port
movie_metadata:
  douban:
    cookie: cookie
  fanart:
    api_key: api_key
    proxies: ''
  tmdb:
    api_key: api_key
    proxies: ''
notify_channel:
  qywx:
    aes_key: aes_key
    agentid: 'agentid'
    corpid: corpid
    corpsecret: corpsecret
    enable: true
    message_template:
      movie_completed:
        message: ${nickname}添加的电影 ${name}(${year})下载完毕
        title: ${name} (${year}) 评分:${rating}
      tv_completed:
        message: ${nickname}添加的剧集 ${name}(${year})第${episodes}集下载完毕
        title: ${name} (${year}) 评分:${rating}
    server_url: https://qyapi.weixin.qq.com
    token: token
    touser: touser
    use_server_proxy: false
scraper: {}
server: {}
smart_download:
  douban:
    default_score_rule: compress
    download_paths:
    - area: []
      cate: []
      download_path: /4T/tmpTV
      score_rule: compress
      type: tv
    - area:
      - 中国大陆
      cate: []
      download_path: /4T/movie/tmp-cn
      score_rule: compress
      type: movie
    - area:
      - 欧美
      cate: []
      download_path: /4T/movie/tmp-en
      score_rule: compress
      type: movie
    - area:
      - 中国香港
      cate: []
      download_path: /4T/movie/tmp-hk
      score_rule: compress
      type: movie
    tags: []
    users:
    - id: id
      pull_time_range: 365
subtitle: {}
web:
  host: '::'
  port: 1329
  server_url: http://

```
