### ISSUE TITLE
[缺陷]: 添加TG推送的一个BUG

### ISSUE THREAD

**Issue by mjyhj** [pofey/movie_robot#652]
### 当前程序版本

1.2.7

### 问题描述

如果之前在base_config.yml里没添加过TG的推送测试
在升级1.2.7后，首次添加TG，会有5行数据
```
  telegram:
    enable: true
    proxy: ''
    server_url: https://api.telegram.org
    token: 5658658888:AAHmxI-ZeZZukZwZZZxIzyZsx8ZZZZqv8mg
    user_id: '934888888'
```

此时proxy是空白，推送测试会报错，估计是等于启用了代理，但是又没填导致的。
得在base_config.yml里删掉proxy: ''这行，重启docker，就正常了

### 重现步骤

删掉base_config.yml里的tg推送，web里重新添加测试，复现

### 健康检查

正常
