### ISSUE TITLE
无法打开网页

### ISSUE THREAD

**Issue by winkee01** [pofey/movie_robot#77]
`docker run -d 1329:1329 yipengfei/movie-robot` 启动后，浏览器中输入 `http://127.0.0.1:1329/setup/admin` 打不开网页。

<img width="519" alt="CleanShot 2022-05-04 at 15 47 03@2x" src="https://user-images.githubusercontent.com/49930785/166641144-902ac404-ab68-4b4e-a70d-ee6318ae58e9.png">

**Comment by LeanFly** [comment]
请看日志

**Comment by winkee01** [comment]
日志就是这样，没显示错误
<img width="1146" alt="CleanShot 2022-05-05 at 00 38 27@2x" src="https://user-images.githubusercontent.com/49930785/166729104-d8eb2920-ef6d-4adf-aad6-fd78280ffc72.png">

**Comment by pofey** [comment]
激活码错误 没激活进不去

**Comment by winkee01** [comment]
> 激活码错误 没激活进不去

怎么激活？ 这是我第一次运行啊，直接就访问不了，我怎么激活。

**Comment by pofey** [comment]
> > 激活码错误 没激活进不去
> 
> 怎么激活？ 这是我第一次运行啊，直接就访问不了，我怎么激活。

环境变量有个key

**Comment by winkee01** [comment]
> > > 激活码错误 没激活进不去
> > 
> > 
> > 怎么激活？ 这是我第一次运行啊，直接就访问不了，我怎么激活。
> 
> 环境变量有个key

具体环境变量是什么啊？ 我没看到文档哪里有介绍啊。

**Comment by pofey** [comment]
> > > > 激活码错误 没激活进不去
> > > 
> > > 
> > > 怎么激活？ 这是我第一次运行啊，直接就访问不了，我怎么激活。
> > 
> > 
> > 环境变量有个key
> 
> 具体环境变量是什么啊？ 我没看到文档哪里有介绍啊。

https://yee329.notion.site/Docker-09e1db16b2b14040840bd2f5660e666c

**Comment by winkee01** [comment]
@pofey 好的，完全没注意这个 wiki 页。

**Comment by pofey** [comment]
> @pofey 有点无语，搞了一下午都没登录上去。transmission 设置页面一直报错说，但我的用户名和密码都是对的啊。
> ![image](https://user-images.githubusercontent.com/49930785/166941470-e00e0f7f-506d-4667-a9c6-673fe9e9ebac.png)

这个页面没啥bug空间，说你错了就是真的错了吧

**Comment by winkee01** [comment]
@pofey 我也觉得很诡异，我的 transmission 是用 docker 部署的，而且我都重新部署了，用户名密码也都在 docker-compose.yml 中写死了。。。

```
version: "3.9"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asian/Shanghai
      - TERM=xterm
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
      - USER=admin
      - PASS=hahX!123
      - WHITELIST=10.10.0.*
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    networks:
      - web
networks:
  web:
    external: true
```
